"use client";
import { estimateMaterialDescription } from "@/lib/estimate-material-description";

import { EstimateBreakdownView } from "./estimate-breakdown-view";
import { EstimateNumberEditor } from "./estimate-number-editor";
import { Fragment, useEffect, useState } from "react";
import { EstimateCostEditor, type EstimateLineItem } from "./estimate-cost-editor";
import { estimateLineTotal as total } from "@/lib/estimate-costs";
import { supabase } from "@/lib/supabase";

export interface PackageDocument { id:string; document_type:string; file_name:string; box_path:string; box_file_id?:string|null; extraction_status:string }

function money(value:number) { return value.toLocaleString("en-US",{style:"currency",currency:"USD"}); }

export function EstimatePackageView({estimate,lines,documents,homeowner,address,phone,email,onSaved}:{
  estimate:{id:string;estimate_number:string;version:number;program_track:string;status:string;total_project_cost:number|null;rebate_amount:number|null;homeowner_out_of_pocket:number|null;ai_confidence:number|null;ai_gap_flags:unknown;validation_checks?:unknown;ai_gap_resolution?:string|null};
  lines:EstimateLineItem[]; documents:PackageDocument[]; homeowner:string; address:string; phone?:string|null; email?:string|null; onSaved:()=>Promise<void>;
}) {
  const [tab,setTab]=useState<"quote"|"cost"|"evidence"|"validation"|"terms"|"comprehensive"|"proposal"|"master">("quote");
  const [resolution,setResolution]=useState(estimate.ai_gap_resolution??'');
  const [resolutionStatus,setResolutionStatus]=useState('');
  const [pdfStatus,setPdfStatus]=useState('');
  const [proposalSplit,setProposalSplit]=useState({labor:45,material:55});
  const estimateLines=lines.filter(l=>l.estimate_id===estimate.id && ["scope","material","labor","fee","adjustment"].includes(l.item_type) && !l.internal_notes?.startsWith('AI candidate only'));
  const customerLines=estimateLines.filter(l=>l.internal_notes !== 'SYSTEM: calculated from workbook pricing assumptions');
  const gaps=Array.isArray(estimate.validation_checks)?estimate.validation_checks.map(String):Array.isArray(estimate.ai_gap_flags)?estimate.ai_gap_flags.map(String):[];
  const confidence=estimate.ai_confidence??0;
  const extractionGaps=Array.isArray(estimate.ai_gap_flags)?estimate.ai_gap_flags.map(String):[];
  async function saveResolution(){setResolutionStatus('Saving…');const {error}=await supabase.from('estimates').update({ai_gap_resolution:resolution.trim()||null}).eq('id',estimate.id);if(!error)await supabase.rpc('recompute_estimate_validation',{p_estimate_id:estimate.id});setResolutionStatus(error?.message??'Saved');if(!error)await onSaved();}
  const scopes=customerLines.filter(l=>l.item_type==='scope');
  useEffect(()=>{let active=true;void supabase.from('estimate_pricing_assumptions').select('labor_split_percent,material_split_percent').eq('estimate_id',estimate.id).maybeSingle().then(({data})=>{if(active&&data)setProposalSplit({labor:Number(data.labor_split_percent??45),material:Number(data.material_split_percent??55)});});return()=>{active=false};},[estimate.id]);
  const proposalChildren=(scope:EstimateLineItem,index:number)=>{const scoped=customerLines.filter(l=>l.parent_line_item_id===scope.id);const scopeTotal=estimateLines.filter(l=>l.parent_line_item_id===scope.id).reduce((sum,l)=>sum+total(l),0);const labor=Math.round(scopeTotal*proposalSplit.labor)/100;const material=Math.round((scopeTotal-labor)*100)/100;const materialDescription=scoped.filter(l=>l.item_type==='material').map(estimateMaterialDescription).filter(Boolean).join('\n\n')||'Materials and equipment required for the described scope.';const laborDescription=scoped.filter(l=>l.item_type==='labor').map(estimateMaterialDescription).filter(Boolean).join('\n\n')||'Labor required to complete, test, inspect, and clean up the described scope.';return [{number:`${index+1}.1`,name:'Materials',description:materialDescription,amount:material},{number:`${index+1}.2`,name:'Labor',description:laborDescription,amount:labor}];};
  const tabs=[['quote','Quotation preview'],['cost','Internal costing'],['comprehensive','Comprehensive cost breakdown'],['proposal','Breakdown for Proposal'],['master','Master Cost Summary'],['evidence','Source evidence'],['validation',`Validation ${confidence}%`],['terms','Terms of Service']] as const;
  const visibleTotal = estimateLines.reduce((sum,line)=>sum+total(line),0);
  const unassigned = estimateLines.some(line=>line.item_type!=="scope" && !scopes.some(scope=>scope.id===line.parent_line_item_id));
  const missingHearEvidence = estimate.program_track === "HEAR" && (!scopes.length || scopes.some(scope=>!scope.sero_scope_document_id || !scope.sero_scope_reference?.trim()));
  const costMismatch = unassigned || Math.abs(visibleTotal-(estimate.total_project_cost??0))>0.01;
  async function downloadPackage(includeTerms = true){
    if (missingHearEvidence) { setPdfStatus("Link every HEAR scope to its audit, site-visit, work-order/specification, or HVAC-design source and enter the applicable reference before downloading."); return; }
    if (costMismatch) { setPdfStatus("Resolve unassigned costs or total mismatch before downloading."); return; }
    try {setPdfStatus('Building package...');const quoteScopes=scopes.map((scope,index)=>({number:String(index+1),name:scope.scope_name||`Scope ${index+1}`,description:scope.description||'',seroScopeReference:scope.sero_scope_reference,seroDocumentId:scope.sero_scope_document_id,subtotal:estimateLines.filter(l=>l.parent_line_item_id===scope.id).reduce((sum,line)=>sum+total(line),0),children:proposalChildren(scope,index)}));const response=await fetch('/api/estimator/contract-package',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({estimateNumber:estimate.estimate_number,estimateDate:new Date().toLocaleDateString('en-US'),programTrack:estimate.program_track,homeowner,address,phone,email,total:estimate.total_project_cost??0,rebate:estimate.rebate_amount??0,outOfPocket:estimate.homeowner_out_of_pocket??0,scopes:quoteScopes,includeTerms,draft:!["approved","sent_for_signature","signed"].includes(estimate.status)})});if(!response.ok){const failure=await response.json();setPdfStatus(failure.error || 'Package generation failed');return;}const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`${estimate.estimate_number.replace(/[^A-Za-z0-9._-]/g,"-")}-${estimate.program_track}-${includeTerms?"Contract-Package":"Quotation"}.pdf`;anchor.click();URL.revokeObjectURL(url);setPdfStatus(includeTerms?'Downloaded with Terms of Service':'Quotation downloaded without Terms of Service');
    } catch { setPdfStatus('Download failed. Please try again.'); }
  }
  return <section className="overflow-hidden rounded-2xl border border-white/10 bg-card">
    {estimate.program_track === "HEAR" && <p className="border-b border-white/10 px-4 py-3 text-xs text-amber-200">Check the applicable SERO rules and reservation status before confirming HEAR eligibility (see the September 1, 2026 program changes). Record the applicable requirement with each equipment item.</p>}
    <EstimateNumberEditor key={`${estimate.id}:${estimate.estimate_number}`} estimateId={estimate.id} estimateNumber={estimate.estimate_number} status={estimate.status} onSaved={onSaved}/>
    <div className="flex flex-wrap gap-1 border-b border-white/10 p-2">{tabs.map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`rounded-lg px-4 py-2 text-sm ${tab===key?'bg-cyan-400 text-slate-950':'text-slate-300 hover:bg-white/5'}`}>{label}</button>)}</div>
    {missingHearEvidence && <p role="alert" className="m-4 rounded-lg border border-amber-400/30 p-3 text-sm text-amber-200">HEAR scope needs supporting evidence. In Internal costing, edit each scope to select its audit, site-visit, work-order/specification, or HVAC-design source and enter the applicable page, measure, finding, or section.</p>}
    {["comprehensive","proposal","master"].includes(tab) && <EstimateBreakdownView view={tab as "comprehensive"|"proposal"|"master"} lines={lines.filter(line=>line.estimate_id===estimate.id)} savedTotal={estimate.total_project_cost} rebate={estimate.rebate_amount} program={estimate.program_track} laborSplit={proposalSplit.labor} materialSplit={proposalSplit.material}/>}
    {tab==='quote'&&<div className="p-4 lg:p-6"><div className="mb-4 flex flex-wrap justify-between gap-3"><div><div className="text-xs uppercase tracking-[.2em] text-cyan-300">Quotation content preview</div><h3 className="mt-1 text-lg font-semibold text-white">{estimate.program_track} Energy Savings Program Quotation</h3><div className="mt-1 text-xs text-slate-400">{pdfStatus}</div></div><div className="flex flex-wrap gap-2"><button disabled={costMismatch || missingHearEvidence} onClick={()=>downloadPackage(false)} className="rounded-lg border border-cyan-400/30 px-3 py-2 text-xs text-cyan-200 disabled:opacity-40">Download quotation only</button><button disabled={costMismatch || missingHearEvidence} onClick={()=>downloadPackage(true)} className="rounded-lg border border-cyan-400/30 px-3 py-2 text-xs text-cyan-200 disabled:opacity-40">Download quotation + Terms PDF</button></div></div>{costMismatch&&<p role="alert" className="mb-4 text-sm text-red-200">Costs do not reconcile with the saved total, or a cost line has no quotation scope. Correct Internal costing before downloading.</p>}
      <article className="mx-auto max-w-[850px] rounded-xl bg-white px-12 py-11 font-[Arial,sans-serif] text-[13px] text-[#444] shadow-xl print:fixed print:inset-0 print:z-50 print:overflow-visible print:rounded-none print:p-10">
        <div className="grid grid-cols-[1.2fr_1fr_auto] gap-5"><div><div className="text-2xl font-light text-orange-500">{["approved","sent_for_signature","signed"].includes(estimate.status)?"ESTIMATE":"DRAFT ESTIMATE"}</div><div className="font-bold">Stonebridge Home Energy Solutions</div><div className="text-sm">4820 Meridian Park Dr, Suite 210<br/>Richmond, VA 23230</div></div><div className="pt-7 text-sm">accounts@stonebridgehomeenergy.com<br/>+1 (804) 555-0148</div><div className="text-right"><img src="/logo/stonebridge-logo.svg" alt="Stonebridge Home Energy Solutions" className="ml-auto w-40" /></div></div>
        <div className="my-7 text-center text-base font-bold">SERO Energy Rebate Program - {estimate.program_track}</div>
        <div className="space-y-5 text-sm"><div><div className="font-bold">Prepared for</div><div>{homeowner}</div><div>{address}</div>{phone&&<div>{phone}</div>}{email&&<div>{email}</div>}</div><div><div className="font-bold">Estimate Details</div><div>Estimate No: {estimate.estimate_number}</div><div>Estimate Date: {new Date().toLocaleDateString('en-US')}</div></div></div>
        <table className="mt-6 w-full table-fixed border-collapse text-left text-xs"><thead><tr className="bg-amber-100"><th className="w-10 border border-slate-500 p-2">#</th><th className="w-1/4 border border-slate-500 p-2">Product or Service</th><th className="border border-slate-500 p-2">Description</th><th className="w-28 border border-slate-500 p-2 text-right">Amount</th></tr></thead><tbody>{scopes.length?scopes.map((scope,index)=>{const children=proposalChildren(scope,index); const scopeTotal=children.reduce((sum,l)=>sum+l.amount,0); return <Fragment key={scope.id}><tr className="align-top"><td className="border border-slate-500 p-2 text-right">{index+1}</td><td className="border border-slate-500 p-2 font-medium">{scope.scope_name}</td><td className="border border-slate-500 p-2 whitespace-pre-line break-words leading-5">{scope.description}</td><td className="border border-slate-500 p-2"/></tr>{children.map(l=><tr key={l.number} className="align-top"><td className="border border-slate-500 p-2 text-right">{l.number}</td><td className="border border-slate-500 p-2">{l.name}</td><td className="border border-slate-500 p-2 whitespace-pre-line break-words leading-5">{l.description}</td><td className="border border-slate-500 p-2 text-right">{money(l.amount)}</td></tr>)}<tr><td colSpan={3} className="border border-slate-500 p-2 font-bold">Subtotal</td><td className="border border-slate-500 p-2 text-right font-bold">{money(scopeTotal)}</td></tr></Fragment>}):<tr><td colSpan={4} className="border border-slate-500 py-10 text-center text-slate-500">No compliant quotation lines yet. Pricing inputs are required.</td></tr>}</tbody></table>
        <div className="ml-auto mt-0 w-full max-w-[295px] border border-slate-500 bg-amber-100 text-xs font-bold"><div className="grid grid-cols-[2fr_1fr] border-b border-slate-500"><span className="border-r border-slate-500 p-2">Total Project Cost</span><span className="p-2 text-right">{money(estimate.total_project_cost??0)}</span></div><div className="grid grid-cols-[2fr_1fr] border-b border-slate-500"><span className="border-r border-slate-500 p-2">Less: {estimate.program_track} Rebate</span><span className="p-2 text-right">{money(estimate.rebate_amount??0)}</span></div><div className="grid min-h-12 grid-cols-[2fr_1fr]"><span className="border-r border-slate-500 p-2">Homeowner Out-of-Pocket</span><span className="p-2 text-right">{money(estimate.homeowner_out_of_pocket??0)}</span></div></div>
        <div className="mt-6 border border-slate-600 p-3 text-xs leading-5">Note: Unforeseen site conditions or hidden safety hazards discovered during the work may require additional out-of-pocket costs to safely resolve. To qualify for the Energy Saver NC rebate, the entire agreed-upon Scope of Work must be completed. The homeowner understands that cancellation rather than addressing required conditions may make the homeowner responsible for costs incurred. Terms of Service are included in the combined package and available separately.</div>
        <div className="mt-8 space-y-5 text-sm"><div className="grid grid-cols-[210px_1fr] items-end"><b>Customer Signature:</b><div className="border-b border-slate-700"/></div><div className="grid grid-cols-[210px_1fr] items-end"><b>Date:</b><div className="border-b border-slate-700"/></div></div>
      </article></div>}
    {tab==='cost'&&<div className="p-4"><EstimateCostEditor estimateId={estimate.id} estimateStatus={estimate.status} lines={lines} documents={documents} programTrack={estimate.program_track} onSaved={onSaved}/></div>}
    {tab==='evidence'&&<div className="grid gap-3 p-5 md:grid-cols-2">{documents.map(d=><div key={d.id} className="rounded-xl border border-white/10 p-4"><div className="text-[10px] uppercase tracking-wider text-cyan-300">{d.document_type.replaceAll('_',' ')}</div><div className="mt-2 break-words text-sm text-white">{d.file_name}</div><div className="mt-1 break-words text-xs text-slate-500">{d.box_path}</div>{d.box_file_id&&<a className="mt-3 inline-block text-xs text-cyan-300 underline" href={`https://app.box.com/file/${d.box_file_id}`} target="_blank" rel="noreferrer">Open source in Box ↗</a>}</div>)}</div>}
    {tab==='validation'&&<div className="space-y-4 p-5"><div className={`rounded-xl border p-5 ${confidence>=95?'border-emerald-400/30 bg-emerald-400/10':'border-amber-400/30 bg-amber-400/10'}`}><div className="text-3xl font-semibold text-white">{confidence}%</div><div className="mt-1 text-sm text-slate-300">Review gate: 95% minimum. Confidence measures package completeness and evidence—not unsupported AI certainty.</div></div><div className="space-y-2">{gaps.length?gaps.map(g=><div key={g} className="rounded-lg border border-amber-400/20 px-3 py-2 text-sm text-amber-200">Needs attention: {g}</div>):<div className="rounded-lg border border-emerald-400/20 px-3 py-2 text-sm text-emerald-200">All required validation checks passed.</div>}</div>{extractionGaps.length>0&&<div className="rounded-xl border border-red-400/20 bg-red-400/5 p-4"><h4 className="text-sm font-semibold text-red-200">Source conflicts and missing information</h4><div className="mt-3 space-y-2">{extractionGaps.map((gap,index)=><p key={index} className="text-xs leading-5 text-slate-300">{gap}</p>)}</div><label className="mt-4 block text-xs text-slate-400">Christina&apos;s documented resolution<textarea rows={4} value={resolution} onChange={e=>setResolution(e.target.value)} className="mt-2 w-full rounded-lg border border-white/10 bg-black/20 p-3 text-sm text-white" placeholder="State how each material conflict was verified or why it does not affect this estimate."/></label><div className="mt-3 flex items-center justify-end gap-3"><span className="text-xs text-slate-400">{resolutionStatus}</span><button onClick={saveResolution} className="rounded-lg border border-cyan-400/30 px-3 py-2 text-xs text-cyan-200">Save resolution and revalidate</button></div></div>}</div>}
    {tab==='terms'&&<div className="p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold text-white">Sample Terms of Service</h3><p className="mt-1 text-xs text-slate-400">Canonical Stonebridge document included in the quotation + Terms download and signing package. The quotation-only download omits it.</p></div><a href="/legal/Sample-Terms-of-Service.pdf" target="_blank" rel="noreferrer" className="rounded-lg border border-cyan-400/30 px-3 py-2 text-xs text-cyan-200">Open exact PDF ↗</a></div><iframe title="Sample Terms of Service" src="/legal/Sample-Terms-of-Service.pdf#view=FitH" className="h-[760px] w-full rounded-xl border border-white/10 bg-white"/></div>}
  </section>;
}
