"use client";

import type { EstimateLineItem } from "./estimate-cost-editor";
import { buildEstimateBreakdowns, COST_CATEGORIES } from "@/lib/estimate-breakdowns";

const money = (value: number) => value.toLocaleString("en-US", { style: "currency", currency: "USD" });

export function EstimateBreakdownView({ lines, savedTotal, rebate, program, view, laborSplit, materialSplit }: {
  lines: EstimateLineItem[]; savedTotal: number | null; rebate: number | null; program: string;
  laborSplit: number; materialSplit: number;
  view: "comprehensive" | "proposal" | "master";
}) {
  const summary = buildEstimateBreakdowns(lines);
  const titles = { comprehensive: "Comprehensive Project Cost Breakdown", proposal: "Breakdown for Proposal", master: "Master Cost Summary" };
  const mismatch = savedTotal == null || Math.abs(summary.total - savedTotal) > .01;
  return <div className="space-y-4 p-4 lg:p-6">
    <div><h3 className="text-lg font-semibold text-white">{titles[view]}</h3><p className="mt-2 text-sm text-slate-400">{program} estimate only. These amounts come from saved cost lines. Saving workbook assumptions calculates Equipment / Minor Tools as 10% of direct labor and creates the overhead, profit, contingency, bonding, mobilization, travel, and county-tax lines.</p></div>
    {(mismatch || summary.hasUnassigned || summary.candidateTotal !== 0) && <div role="alert" className="rounded-xl border border-amber-400/30 p-3 text-sm text-amber-200">{mismatch && `Saved project total ${money(savedTotal ?? 0)} differs from included costs ${money(summary.total)}. `}{summary.hasUnassigned && "Assign every cost line to a scope. "}{summary.candidateTotal !== 0 && `Unverified candidate costs excluded: ${money(summary.candidateTotal)}.`}</div>}
    {view === "comprehensive" ? <table className="w-full max-w-3xl text-sm"><tbody>{COST_CATEGORIES.map(([key,label]) => <tr key={key} className="border-b border-white/10"><th className="py-3 pr-4 text-left font-normal text-slate-300">{label}</th><td className="py-3 text-right tabular-nums text-white">{money(summary.totals[key])}</td></tr>)}</tbody><tfoot><tr className="bg-amber-400/10 font-semibold text-amber-100"><th className="p-3 text-left">Overall Total Project Cost</th><td className="p-3 text-right tabular-nums">{money(summary.total)}</td></tr></tfoot></table>
      : view === "proposal" ? <><p className="text-xs text-slate-400">The homeowner proposal allocates each fully loaded scope total using the saved workbook split: {laborSplit}% Labor and {materialSplit}% Materials.</p><div className="overflow-x-auto rounded-xl border border-white/10"><table className="w-full min-w-[560px] text-sm"><thead className="bg-white/5 text-slate-300"><tr>{["Scope", "Labor", "Material", "Total"].map((label,i) => <th key={label} className={`p-3 ${i ? "text-right" : "text-left"}`}>{label}</th>)}</tr></thead><tbody>{summary.rows.map(row => {const labor=Math.round(row.total*laborSplit)/100;const material=Math.round((row.total-labor)*100)/100;return <tr key={row.id} className="border-t border-white/10"><th className="p-3 text-left font-normal text-white">{row.name}</th><td className="p-3 text-right tabular-nums">{money(labor)}</td><td className="p-3 text-right tabular-nums">{money(material)}</td><td className="p-3 text-right font-semibold tabular-nums">{money(row.total)}</td></tr>})}</tbody><tfoot className="border-t border-white/10 bg-amber-400/10 font-semibold"><tr><th className="p-3 text-left">Total</th><td className="p-3 text-right">{money(Math.round(summary.total*laborSplit)/100)}</td><td className="p-3 text-right">{money(Math.round((summary.total-Math.round(summary.total*laborSplit)/100)*100)/100)}</td><td className="p-3 text-right">{money(summary.total)}</td></tr></tfoot></table></div></>
      : <div className="overflow-x-auto rounded-xl border border-white/10"><table className="w-full min-w-[1800px] text-xs"><thead className="bg-white/5 text-slate-300"><tr><th rowSpan={2} className="min-w-56 p-3 text-left">Scope</th><th colSpan={4} className="border-l border-white/10 p-3 text-center">Direct Costs</th><th colSpan={8} className="border-l border-white/10 p-3 text-center">Soft Costs and Adjustments</th><th rowSpan={2} className="p-3 text-right">Total Cost</th></tr><tr>{COST_CATEGORIES.map(([key,label]) => <th key={key} className="min-w-28 p-3 text-right">{label}</th>)}</tr></thead><tbody>{summary.rows.map(row => <tr key={row.id} className="border-t border-white/10"><th className="p-3 text-left font-normal text-white">{row.name}</th>{COST_CATEGORIES.map(([key])=><td key={key} className="p-3 text-right tabular-nums">{money(row.costs[key])}</td>)}<td className="p-3 text-right font-semibold tabular-nums">{money(row.total)}</td></tr>)}</tbody><tfoot className="bg-amber-400/10 font-semibold"><tr><th className="p-3 text-left">Total Cost</th>{COST_CATEGORIES.map(([key])=><td key={key} className="p-3 text-right tabular-nums">{money(summary.totals[key])}</td>)}<td className="p-3 text-right tabular-nums">{money(summary.total)}</td></tr></tfoot></table></div>}
    <dl className="ml-auto grid max-w-md grid-cols-[1fr_auto] gap-x-6 gap-y-2 rounded-xl border border-white/10 p-4 text-sm"><dt>Total Project Cost</dt><dd className="text-right tabular-nums">{money(summary.total)}</dd><dt>Less: {program} Rebate (saved)</dt><dd className="text-right tabular-nums">{rebate == null ? "Not confirmed" : money(rebate)}</dd><dt>Homeowner Out-of-Pocket</dt><dd className="text-right font-semibold tabular-nums">{mismatch || rebate == null ? "Reconcile estimate first" : money(Math.max(summary.total-rebate,0))}</dd></dl>
  </div>;
}
